MODULE Enrollment;
REQUIRE Student, Lesson;

CLASS enrollment 'Запись';
student = DATA Student (enrollment);
lesson = DATA Lesson (enrollment);


studentEnroll = DATA LOCAL STRING[100];
lessonEnroll = DATA LOCAL STRING[100];

applyToLesson 'Запись' (FILE f) {
    IMPORT JSON CHARSET 'utf-8' FROM f TO() studentEnroll, lessonEnroll;
    IF NOT enrollByName(studentEnroll()) THEN 
            EXPORT JSON FROM success = NULL, msg = 'No student\'s name';
    IF NOT enrollByName(studentEnroll()) THEN BREAK;
    
    IF NOT enrollToSubject(lessonEnroll()) THEN
            EXPORT JSON FROM success = NULL, msg = 'Subject is not selected';
    IF NOT enrollToSubject(lessonEnroll()) THEN BREAK;
    
    NEW apply = enrollment {
        student(apply) <- enrollByName(studentEnroll());
        lesson(apply) <- enrollToSubject(lessonEnroll());
    }
    APPLY;
    EXPORT JSON FROM success = TRUE, msg = 'You successfully applied to lesson';
}
