MODULE Lesson;
REQUIRE Tutor, Subject;

CLASS Lesson 'Урок';
topic 'Тема' = DATA STRING[50] (Lesson);
dateTime 'Дата-время' = DATA DATETIME (Lesson);

subject 'Предмет' = DATA Subject (Lesson);
nameSubject 'Предмет' (Lesson l) = name(subject(l));
tutor 'Репетитор' = DATA Tutor (Lesson);
nameTutor 'Репетитор' (Lesson l) = fullname(tutor(l));


FORM lessons 'Уроки'
    OBJECTS l = Lesson
    PROPERTIES(l) topic, dateTime, nameSubject, nameTutor, NEW, DELETE;
